DROP ALL OBJECTS;

CREATE TABLE SMART_USER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100),
  PASSWORD VARCHAR(100),
  ROLES VARCHAR(100),
  FIRST_NAME VARCHAR(100),
  MIDDLE_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  GENDER VARCHAR(100),
  DOB DATE,
  PHONE VARCHAR(100),
  EMAIL VARCHAR(100),
  PROC_TS TIMESTAMP,
  PROC_APP_ID VARCHAR(50),
  PROC_USER_ID VARCHAR(50),
  PROC_USER_IP_ADDRESS VARCHAR(50),
  PROC_USER_LATITUDE VARCHAR(100),
  PROC_USER_LONGITUDE VARCHAR(100),
  VERS_ID smallint NOT NULL
);
